name: CI
on:
  push:
    branches: 
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-18.04



      - name: Install requirements
        run: |
          pip3 install -r requirements.txt
          coverage run -m unittest discover
          COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS }} coveralls
