name: CI
on:
  push:
    branches: 
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Install requirements
        run: |
          git clone https://github.com/Veritaris/AppVeloxTC.git
          cd AppVeloxTC
          pip3 install setuptools
          pip3 install -r requirements.txt
          pip3 install coveralls
          coverage run -m unittest discover
          COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS }} coveralls
