name: CI
on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: start deploy script via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ./deploy.sh
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
